services:
    
  ollama:
    image: 840110/gestionit_ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/data
    restart: always

    
        
  apidb:
    container_name: gestionIt_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "8002:1433"
    env_file:
      - .env
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${DB_PASSWORD}
    volumes:
    - db_data:/var/opt/mssql

  web:
    image: 840110/gestionit_front:IA
    build:
      context: ../SISINF/
      dockerfile: ../SISINF/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  ../SISINF/nginx/cert.pem:/etc/nginx/cert.pem:ro
      -  ../SISINF/nginx/privkey.pem:/etc/nginx/privkey.pem:ro
      -  ../SISINF/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - .env
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_DEBUG=${REACT_APP_DEBUG}
    restart: always
  
  api:
    image: 840110/gestionit_api:IA
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - apidb
    environment:
      - DB_HOST=apidb
      - DB_NAME=gestionIt_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - BASE_URL=${BASE_URL}
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  db_data:
  ollama-data:
    driver: local  

