services:
  apidb:
    container_name: gestionIt_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "8002:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    volumes:
    - db_data:/var/opt/mssql
  
  api:
    image: 840110/gestionit_api:latest
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - apidb
    environment:
      - DB_HOST=apidb
      - DB_NAME=gestionIt_db
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  db_data:

